name: milisav_dyadic_communication
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - brotlipy=0.7.0
  - c-ares=1.18.1
  - ca-certificates=2022.9.24
  - cached-property=1.5.2
  - cached_property=1.5.2
  - certifi=2022.9.24
  - cffi=1.15.1
  - chardet=5.0.0
  - charset-normalizer=2.1.1
  - colorama=0.4.6
  - cryptography=38.0.2
  - h5py=3.7.0
  - hdf5=1.12.2
  - icu=70.1
  - idna=3.4
  - joblib=1.2.0
  - keyutils=1.6.1
  - krb5=1.19.3
  - ld_impl_linux-64=2.39
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcurl=7.86.0
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.4.2
  - libgcc-ng=12.2.0
  - libgfortran-ng=12.2.0
  - libgfortran5=12.2.0
  - libgomp=12.2.0
  - libiconv=1.17
  - liblapack=3.9.0
  - libnghttp2=1.47.0
  - libnsl=2.0.0
  - libopenblas=0.3.21
  - libsqlite=3.40.0
  - libssh2=1.10.0
  - libstdcxx-ng=12.2.0
  - libxml2=2.10.3
  - libxslt=1.1.37
  - libzlib=1.2.13
  - lxml=4.9.1
  - ncurses=6.3
  - nibabel=4.0.2
  - nilearn=0.9.2
  - numpy=1.21.6
  - openssl=3.0.7
  - packaging=21.3
  - pandas=1.3.5
  - pip=22.3.1
  - pycparser=2.21
  - pydicom=2.3.1
  - pyopenssl=22.1.0
  - pyparsing=3.0.9
  - pysocks=1.7.1
  - python=3.7.12
  - python-dateutil=2.8.2
  - python_abi=3.7
  - pytz=2022.6
  - readline=8.1.2
  - requests=2.28.1
  - scikit-learn=1.0.2
  - scipy=1.7.3
  - setuptools=59.8.0
  - six=1.16.0
  - sqlite=3.40.0
  - threadpoolctl=3.1.0
  - tk=8.6.12
  - tqdm=4.64.1
  - urllib3=1.26.11
  - wheel=0.38.4
  - xz=5.2.6
  - zlib=1.2.13
  - pip:
    - aiohttp==3.8.3
    - aiosignal==1.2.0
    - apptools==5.2.0
    - async-timeout==4.0.2
    - asynctest==0.13.0
    - attrs==22.1.0
    - bctpy==0.5.2
    - configobj==5.0.6
    - cycler==0.10.0
    - envisage==6.1.0
    - frozenlist==1.3.1
    - importlib-metadata==4.12.0
    - importlib-resources==5.9.0
    - kaleido==0.2.1
    - kiwisolver==1.3.2
    - matplotlib==3.4.3
    - pyqt5==5.15.7
    - pyqt5-qt5==5.15.2
    - pyqt5-sip==12.11.0
    - vtk==9.1.0
    - mayavi
    - multidict==6.0.2
    - netneurotools==0.2.3
    - pillow==8.4.0
    - plotly==5.10.0
    - pyface==7.4.2
    - pygments==2.13.0
    - pysurfer==0.11.0
    - seaborn==0.12.0
    - tenacity==8.1.0
    - traits==6.4.1
    - traitsui==7.4.0
    - typing-extensions==4.3.0
    - wslink==1.8.2
    - yarl==1.8.1
    - zipp==3.8.1
